name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test ./...

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    ## checks out our project source code
    - uses: actions/checkout@v2
    
    ## Builds our docker image!
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    ## checks out our project source code
    - uses: actions/checkout@v2

    ## Publishes our image to Docker Hub 
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        ## the name of our image
        name: anuragkumarkroger/demo
        ## Here we pass in our Docker Username
        username: ${{ secrets.DOCKER_USERNAME }}
        ## and our Docker password which 
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
