name : Test, Build and Deploy on Docker Hub
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps: 
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
      - run: docker build . --tag my-image-name:$(date +%s)
    

      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: forbsey/go-github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
